name: test-book

# Only run this when the master branch changes
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

# This job installs dependencies and makes sure the book builds.
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2

    # Install dependencies 
    - name: Set up Python 3.11 
      uses: actions/setup-python@v1 
      with: 
        python-version: 3.11
        
    - name: Install dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: tutorial
        environment-file: environment.yml
    # Build the book
    - name: Build the book
      run: |
        conda activate tutorial
        jupyter-book build .